# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0005_merge'),
        ('findings', '0003_auto_20160119_1021'),
    ]

    operations = [
    ]
