# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-09 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0008_add_authz_structure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finding',
            options={'permissions': (('handle_findings', 'Can handle findings'), ('report_observations', 'Can report observations'), ('view_findings', 'Can view findings'), ('view_statistics', 'Can view statistics'))},
        ),
    ]
