# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-14 13:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('findings', '0009_add_finding_permissions'),
        ('fir_notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(max_length=60, verbose_name='observation')),
                ('method', models.CharField(max_length=60, verbose_name='method')),
                ('business_lines', models.ManyToManyField(blank=True, related_name='_notificationpreference_business_lines_+', to='findings.BusinessLine', verbose_name='business lines')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
            },
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together=set([('user', 'observation', 'method')]),
        ),
        migrations.AlterIndexTogether(
            name='notificationpreference',
            index_together=set([('user', 'observation', 'method')]),
        ),
    ]
